# Generated by Django 6.0.2 on 2026-03-04 16:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("file", "File"), ("db", "Database")],
                        default="file",
                        max_length=20,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "file_format",
                    models.CharField(
                        blank=True,
                        choices=[("csv", "CSV"), ("xlsx", "XLSX"), ("json", "JSON")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("import_settings", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Experiment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("hypothesis", models.TextField(blank=True, null=True)),
                ("metric_column", models.CharField(max_length=255)),
                ("group_column", models.CharField(max_length=255)),
                (
                    "alpha",
                    models.DecimalField(
                        decimal_places=3, default="0.050", max_digits=4
                    ),
                ),
                (
                    "test_type",
                    models.CharField(
                        choices=[("t_test", "T-test"), ("z_test", "Z-test")],
                        max_length=20,
                    ),
                ),
                ("srm_enabled", models.BooleanField(default=False)),
                ("cuped_enabled", models.BooleanField(default=False)),
                (
                    "cuped_covariate",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("config", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExperimentResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                ("n_control", models.IntegerField()),
                ("n_variant", models.IntegerField()),
                (
                    "mean_control",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "mean_variant",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "effect_abs",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "effect_rel",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "p_value",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "ci_low",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "ci_high",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "srm_p_value",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "cuped_theta",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("significant", "Significant"),
                            ("not_significant", "Not Significant"),
                        ],
                        max_length=20,
                    ),
                ),
                ("report_json", models.JSONField(blank=True, null=True)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="core.experiment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("raw", "Raw"),
                            ("cleaned", "Cleaned"),
                            ("transformed", "Transformed"),
                            ("ready", "Ready"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("is_ready_for_analysis", models.BooleanField(default=False)),
                (
                    "storage_type",
                    models.CharField(
                        choices=[("file", "File"), ("jsonb", "JSONB")],
                        default="file",
                        max_length=20,
                    ),
                ),
                ("data_path", models.TextField(blank=True, null=True)),
                ("data_json", models.JSONField(blank=True, null=True)),
                ("preview_rows", models.JSONField(blank=True, null=True)),
                ("row_count", models.IntegerField(blank=True, null=True)),
                ("column_count", models.IntegerField(blank=True, null=True)),
                ("step_config", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="core.dataset",
                    ),
                ),
                (
                    "parent_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="core.snapshot",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="experiment",
            name="snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experiments",
                to="core.snapshot",
            ),
        ),
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("layout", models.JSONField(blank=True, null=True)),
                ("global_filters", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboards",
                        to="core.snapshot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ColumnMetadata",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "inferred_type",
                    models.CharField(
                        choices=[
                            ("int", "Integer"),
                            ("float", "Float"),
                            ("string", "String"),
                            ("date", "Date"),
                            ("bool", "Boolean"),
                        ],
                        max_length=50,
                    ),
                ),
                ("nullable", models.BooleanField(default=False)),
                ("distinct_count", models.IntegerField(blank=True, null=True)),
                ("missing_count", models.IntegerField(blank=True, null=True)),
                ("stats", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="column_metadata",
                        to="core.snapshot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Validation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rule_name", models.CharField(max_length=200)),
                ("rule_params", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("warn", "Warn"),
                        ],
                        max_length=20,
                    ),
                ),
                ("failed_count", models.IntegerField(blank=True, null=True)),
                ("sample_errors", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validations",
                        to="core.snapshot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("line", "Line"),
                            ("bar", "Bar"),
                            ("pie", "Pie"),
                            ("table", "Table"),
                            ("hist", "Histogram"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("x", models.CharField(blank=True, max_length=255, null=True)),
                ("y", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "aggregation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sum", "Sum"),
                            ("avg", "Average"),
                            ("count", "Count"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("group_by", models.CharField(blank=True, max_length=255, null=True)),
                ("filters", models.JSONField(blank=True, null=True)),
                ("options", models.JSONField(blank=True, null=True)),
                ("position", models.JSONField(blank=True, null=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charts",
                        to="core.dashboard",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["dashboard"], name="core_chart_dashboa_cfc3f0_idx"
                    ),
                    models.Index(
                        fields=["chart_type"], name="core_chart_chart_t_9f06be_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="dataset",
            index=models.Index(
                fields=["owner", "created_at"], name="core_datase_owner_i_3ef3a2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dataset",
            unique_together={("owner", "name")},
        ),
        migrations.AddIndex(
            model_name="experimentresult",
            index=models.Index(
                fields=["experiment", "computed_at"],
                name="core_experi_experim_db3dca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="experimentresult",
            index=models.Index(
                fields=["decision"], name="core_experi_decisio_f9f499_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="snapshot",
            index=models.Index(
                fields=["dataset", "created_at"], name="core_snapsh_dataset_76e3f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="snapshot",
            index=models.Index(
                fields=["is_active"], name="core_snapsh_is_acti_45aa5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="snapshot",
            index=models.Index(
                fields=["is_ready_for_analysis"], name="core_snapsh_is_read_663389_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="experiment",
            index=models.Index(
                fields=["owner", "status", "created_at"],
                name="core_experi_owner_i_f806cb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="experiment",
            index=models.Index(
                fields=["snapshot"], name="core_experi_snapsho_7d3f95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dashboard",
            index=models.Index(
                fields=["owner", "created_at"], name="core_dashbo_owner_i_6e9418_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dashboard",
            index=models.Index(
                fields=["snapshot"], name="core_dashbo_snapsho_b13893_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="columnmetadata",
            index=models.Index(
                fields=["snapshot"], name="core_column_snapsho_72c3f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="columnmetadata",
            index=models.Index(fields=["name"], name="core_column_name_1dd62c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="columnmetadata",
            unique_together={("snapshot", "name")},
        ),
        migrations.AddIndex(
            model_name="validation",
            index=models.Index(
                fields=["snapshot"], name="core_valida_snapsho_e0cf47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="validation",
            index=models.Index(fields=["status"], name="core_valida_status_ff395d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="validation",
            unique_together={("snapshot", "rule_name")},
        ),
    ]
